#tell-returns current position and seek()
file=open("myfile.txt",'r+')
str=input("Enter file contents:")
file.write(str)
var=file.tell()
print(var)
file.read()
var2=file.seek(0)
print(var2)
print(file.tell())
var3=file.seek(5,2)
print(var3)